kind: pipeline
type: docker
name: CI

steps:
  - name: restore-cache
    image: plugins/s3-cache
    settings:
      pull: true
      restore: true
      endpoint: https://s3.mnavarro.dev
      bucket: drone-cache
      region: eu-west-1
      path: /drone-cache/legatus/composer
      access_key:
        from_secret: s3_access_key
      secret_key:
        from_secret: s3_secret_key

  - name: build-and-test
    image: composer:latest
    commands:
     - composer config cache-dir .cache
     - composer install --no-progress
     - composer ci

  - name: rebuild-cache
    image: plugins/s3-cache
    settings:
      pull: true
      rebuild: true
      endpoint: https://s3.mnavarro.dev
      path: /drone-cache/legatus/composer
      region: eu-west-1
      access_key:
        from_secret: s3_access_key
      secret_key:
        from_secret: s3_secret_key
      mount:
        - .cache
      when:
        event: push